{
 "title": "Monobank",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Client",
    "query": {
     "query": "label_values(monobank_balance, name)"
    }
   },
   {
    "name": "cardType",
    "label": "Card",
    "query": {
     "query": "label_values(monobank_balance, card_type)"
    }
   },
   {
    "name": "currencyType",
    "label": "Currency",
    "query": {
     "query": "label_values(monobank_balance, currency_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "monobank_balance{name=~\"$name\", currency_type=~\"$currencyType\", card_type=~\"$cardType\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total balance $currencyType",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(monobank_balance{name=~\"$name\", currency_type=~\"$currencyType\", card_type=~\"$cardType\"})"
    }
   ]
  },
  {
   "title": "Currency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "monobank_currencies_buy{currency_a=\"USD\", currency_b=\"UAH\"}",
     "legendFormat": "Buy $"
    },
    {
     "expr": "monobank_currencies_sell{currency_a=\"USD\", currency_b=\"UAH\"}",
     "legendFormat": "Sell $"
    },
    {
     "expr": "monobank_currencies_buy{currency_a=\"EUR\", currency_b=\"UAH\"}",
     "legendFormat": "Buy €"
    },
    {
     "expr": "monobank_currencies_sell{currency_a=\"EUR\", currency_b=\"UAH\"}",
     "legendFormat": "Sell €"
    }
   ]
  },
  {
   "title": "Buy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monobank_currencies_buy{currency_a=\"USD\", currency_b=\"UAH\"}"
    }
   ]
  },
  {
   "title": "Sell",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monobank_currencies_sell{currency_a=\"USD\", currency_b=\"UAH\"}"
    }
   ]
  },
  {
   "title": "Buy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monobank_currencies_buy{currency_a=\"EUR\", currency_b=\"UAH\"}"
    }
   ]
  },
  {
   "title": "Sell",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monobank_currencies_sell{currency_a=\"EUR\", currency_b=\"UAH\"}"
    }
   ]
  }
 ]
}