version: '3.1'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    links:
      - prometheus
    volumes:
      - './configs/datasources.yaml:/etc/grafana/provisioning/datasources/default.yaml'
    depends_on:
      - prometheus
      - exporter
      - redis
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=12345

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    networks:
      - monitoring
    ports:
      - 9090:9090
    volumes:
      - './configs/prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    depends_on:
      - exporter
      - redis

  exporter:
    image: thegarmr/monobank-exporter:latest
    container_name: monobank-exporter
    restart: always
    networks:
      - monitoring
    volumes:
      - ./configs/exporter.yml:/etc/monobank-exporter/monobank-exporter.yml
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: monobank-exporter-redis
    restart: always
    networks:
      - monitoring

networks:
  monitoring:
    external: true
