monobank-exporter:
  clients:
    - name: "John"
      token: "yourToken"
    - name: "Briana"
      token: "yourToken"
  webhookUrl: "http://yourUrl/webhook"
  clientsRefreshTimeInMinutes: 60
  currenciesRefreshTimeInMinutes: 720
